Initial version
PureClarity/pureclarity-x-cart pull request #1
Opened 2020-01-27 16:04 UTC by pcGarethJames

Version 1 of the X-cart integration module

2020-01-30 14:06 UTC, PeterBrooksbank requested changes
Few minor pieces

2020-01-30 14:06 UTC, PeterBrooksbank commented on classes/XLite/Module/PureClarity/Personalization/View/Model/Admin/Dashboard/Signup.php
> +                    $value = 'http://' . $domain;
Is this always going to return http for the store url?

2020-01-30 14:06 UTC, PeterBrooksbank commented on classes/XLite/Module/PureClarity/Personalization/Core/Task/Signup.php
> +        return static::t('PureClarity Sign up check');
Why capital S but not for the other words?

2020-01-31 13:28 UTC, pcGarethJames commented on classes/XLite/Module/PureClarity/Personalization/View/Model/Admin/Dashboard/Signup.php
> +                    $value = 'http://' . $domain;
yes, fixed now though :) it'll return https if the store has https enabled

2020-01-31 13:29 UTC, pcGarethJames commented on classes/XLite/Module/PureClarity/Personalization/Core/Task/Signup.php
> +        return static::t('PureClarity Sign up check');
typo :P, fixed

2020-01-31 14:23 UTC, PeterBrooksbank approved these changes
LGTM

2020-01-31 14:40 UTC, merged